In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [2]:
# dataframe - df
df = pd.read_csv('https://raw.githubusercontent.com/VidushB/2023MLSummerSchool/main/Day2/ML23_session2.csv')
# df = df.dropna()

In [7]:
df.head(20)

,Name,Class,City,Movie,Rating,Genre,Coding Exp
0,Igor P.,Rising Sophomore,"Brooklyn, NY",Moneyball,7.6,Biography,2.0
1,Grant F.,Rising Senior,"Dallas,TX",No Country for Old Men,8.2,Thriller,5.0
2,Matthew K.,Rising Junior,"Old Tappan, NJ",Gurdians of the Galaxy,8.0,Sci-Fi,2.0
3,Blake,Rising Junior,"Grand Junction, Co",Spider-man,7.4,Sci-Fi,1.2
4,Jesse B,Rising Senior,NYC,My Cousin Vinny,7.6,Comedy,3.5
5,Brigitte,Rising Senior,NYC,Welcome to the Dollhouse,7.4,Drama,1.0
6,Zane,Rising sophmore,"Old Tappan, NJ",Iron man 1,7.9,Sci-Fi,3.0
7,Henri S.,Rising Freshman,San Francisco,Grand Budapest Hotel,8.1,Comedy,1.5
8,Mrinalini,Rising Sophmore,"Mount Olive, NJ",Interstellar,8.7,Sci-Fi,3.0
9,Alyssum W.,Rising Junior,"Irvington, NY",Spider-man nwh,8.2,Action,2.0
10,Ami,Rising junior,Nyc,Harry Potter,8.0,Fantasy,3.0
11,Ritvik,Rising Junior,"Millburn/Short Hills, NJ",Star Wars: ROTS,7.6,Sci-Fi,4.0
12,Nailah,Rising Senior,"LI, NY",Karate Kid,7.3,drama,2.0
13,Tristan,Rising Junior,San Francisco,The Thing,8.2,Horror,4.0
14,Aziz A.,Rising Junior,"Long Island, NY",Your Name,8.4,Slice Of Life,3.0
15,Filippos,Rising Junior,NY,Gattaca,7.8,Dystopian,3.0
16,Arhum,Rising Senior,"Jersey City, NJ",Iron Man,7.9,Sci-Fi,4.0
17,Jeronimo,Rising Senior,"Bogota, Col",Star Wars III,7.6,Sci-fi,3.0
18,Alfred,Rising Junior,"Staten Island, NY",Black Hawk Down,7.7,War,3.0
19,Michael,Rising Junior,"Manhattan, NY",Saving Private Ryan,8.6,comedy,3.0

In [12]:
df.loc[df["Class"] == "Rising Senior", "Class"] = 12
df.loc[df["Class"] == "Rising Junior", "Class"] = 11
df.loc[df["Class"] == "Rising Sophmore", "Class"] = 10

In [9]:
df.head()

,Name,Class,City,Movie,Rating,Genre,Coding Exp
0,Igor P.,Rising Sophomore,"Brooklyn, NY",Moneyball,7.6,Biography,2.0
1,Grant F.,Rising Senior,"Dallas,TX",No Country for Old Men,8.2,Thriller,5.0
2,Matthew K.,Rising Junior,"Old Tappan, NJ",Gurdians of the Galaxy,8.0,Sci-Fi,2.0
3,Blake,Rising Junior,"Grand Junction, Co",Spider-man,7.4,Sci-Fi,1.2
4,Jesse B,Rising Senior,NYC,My Cousin Vinny,7.6,Comedy,3.5

In [13]:
df.head

<bound method NDFrame.head of           Name             Class                      City  \
0      Igor P.  Rising Sophomore              Brooklyn, NY
1     Grant F.                12                 Dallas,TX
2   Matthew K.                11            Old Tappan, NJ
3        Blake                11        Grand Junction, Co
4      Jesse B                12                       NYC
5     Brigitte                12                       NYC
6         Zane   Rising sophmore            Old Tappan, NJ
7     Henri S.   Rising Freshman            San Francisco
8    Mrinalini                10           Mount Olive, NJ
9   Alyssum W.                11             Irvington, NY
10         Ami     Rising junior                       Nyc
11      Ritvik                11  Millburn/Short Hills, NJ
12      Nailah                12                    LI, NY
13     Tristan                11             San Francisco
14     Aziz A.                11           Long Island, NY
15    Filippos                11                        NY
16       Arhum                12           Jersey City, NJ
17    Jeronimo                12               Bogota, Col
18      Alfred                11         Staten Island, NY
19     Michael                11             Manhattan, NY
20     Jeremy     Rising Senior                  Dubai,UAE
21       Aaron                11           Shanghai, China

                       Movie  Rating          Genre  Coding Exp
0                  Moneyball     7.6      Biography         2.0
1     No Country for Old Men     8.2       Thriller         5.0
2     Gurdians of the Galaxy     8.0         Sci-Fi         2.0
3                 Spider-man     7.4         Sci-Fi         1.2
4            My Cousin Vinny     7.6         Comedy         3.5
5   Welcome to the Dollhouse     7.4          Drama         1.0
6                 Iron man 1     7.9         Sci-Fi         3.0
7       Grand Budapest Hotel     8.1         Comedy         1.5
8               Interstellar     8.7         Sci-Fi         3.0
9             Spider-man nwh     8.2         Action         2.0
10              Harry Potter     8.0        Fantasy         3.0
11           Star Wars: ROTS     7.6         Sci-Fi         4.0
12                Karate Kid     7.3         drama          2.0
13                 The Thing     8.2         Horror         4.0
14                 Your Name     8.4  Slice Of Life         3.0
15                   Gattaca     7.8      Dystopian         3.0
16                  Iron Man     7.9         Sci-Fi         4.0
17             Star Wars III     7.6         Sci-fi         3.0
18           Black Hawk Down     7.7            War         3.0
19       Saving Private Ryan     8.6         comedy         3.0
20                  sinister     6.8         horror         3.5
21                 Inception     8.8         Action         3.0  >

### Plot the IMDB scores for all the movies
- Use the [plt.scatter() function](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.scatter.html)
- x-axis indicates the name of the movies, y-axis shows the score.
- do not forget to put on the labels for the axes.

In [ ]:
names = df['Movie'].values
score = df['IMDB Score'].values

In [ ]:
## To-do
plt.figure(figsize=(15, 5))
plt.scatter(names, score)
plt.xticks(rotation=90)
plt.show()

### Plot the number of movies for each genre
- Use the [plt.bar() function](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.bar.html)
- x-axis indicates the genre, y-axis shows the count for each genre.
- do not forget to put on the labels for the axes.

In [ ]:
# To-do
genre = df['Genre'].values

modes, counts = np.unique(genre, return_counts=True)

In [ ]:
plt.bar(modes, counts)
plt.xticks(modes, rotation=90)
plt.xlabel('Genre')
plt.ylabel('Count')

### Plot the histogram for the IMDB score
- Use [plt.hist() function](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html)
- x-axis indicates the score interval, y-axis shows the number of movies within each score interval
- make the interval length 0.5
- do not forget to put on the labels for the axes.

- numpy arange() might come in handy!

In [ ]:
# To-do
min_score = np.min(score)
max_score = np.max(score)

bin_range = np.arange(min_score, max_score, 0.5)
plt.hist(score, bin_range, ec='red')

plt.xlabel('Score')
plt.ylabel('Number')
plt.show()

### Calculate the mean and variance of the IMDB score of the movies

In [ ]:
# To-do
mean_score = np.mean(score)
var_score = np.var(score)

print("Mean score: ", mean_score)
print("Var of score: ", var_score)